# Backend Dockerfile for .NET 8 Web API
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Source/API/WebAPI/WebAPI.csproj", "Source/API/WebAPI/"]
COPY ["AWSDemo/AWSDemo.csproj", "AWSDemo/"]
COPY ["Common/Common.csproj", "Common/"]
COPY ["Source/API/DesignPatternsDemo/DesignPatternsDemo.csproj", "Source/API/DesignPatternsDemo/"]
RUN dotnet restore "./Source/API/WebAPI/WebAPI.csproj"
COPY . .
WORKDIR "/src/Source/API/WebAPI"
RUN dotnet build "./WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebAPI.dll"]